name: feature

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest 

    env:
      Solution_Name: src\GenshinCompanion.sln
      Project_Path: src\GenshinCompanion\GenshinCompanion.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Get Project Version
      uses: naminodarie/get-net-sdk-project-versions-action@v1.1.1
      id: get-version
      with:
        proj-path: ${{env.Project_Path}}

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the application
      run: dotnet build --no-restore $env:Solution_Name /p:Configuration=$env:Configuration /p:DeployOnBuild=true /p:PublishProfile="win-x86.pubxml"
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Publish the application
      run: dotnet publish $env:Solution_Name /p:PublishProfile="win-x86" -f netcoreapp3.1

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: GenshinCompanion-${{steps.get-version.outputs.version}}-${{env.Configuration}}
        path: src\GenshinCompanion\bin\${{env.Configuration}}\netcoreapp3.1\publish\win-x86\
        retention-days: 30
      env:
        Configuration: ${{ matrix.configuration }}